version: '2'


services:
        mariadb:
                build: requirements/mariadb 	
                image: i_mariadb
                container_name: mariadb
                volumes:                       
                         - mariadb:/var/lib/mysql
                networks:
                        - inception            			#network
                env_file: .env                  #env variables file
                restart: unless-stopped         #restart if it stops 
                ports:
                    - "3306:3306"
        nginx:
                build: requirements/nginx
                image: i_nginx
                container_name: nginx
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - inception
                env_file: .env
                restart: on-failure 		#redemerer ssi en cas de crash 
                ports:
                        - "443:443" 		#on indique le port qui sera exposé a la machine locale
                depends_on:        			 #do not start nginx until wordpress is already started 
                        - wordpress
        wordpress:
                build: requirements/wordpress
                image: i_wordpress
                container_name: wordpress
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - inception
                env_file: .env
                restart: on-failure
                ports:
                  - "9000:9000"
                depends_on:    				
                        - mariadb



networks:
        inception:
                driver: bridge

volumes:
        wordpress:
                driver: local #in this volume
                driver_opts:
                        type: 'none' 
                        device: '/home/admansar/data/wordpress' 
                        o: 'bind' #bind mount, means that its directly mapped to the directory with the container 
        mariadb:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '/home/admansar/data/mariadb'		

