
services:
        mariadb:
                build: requirements/mariadb 	
                image: mariadb:1337
                container_name: mariadb
                volumes:                       
                         - mariadb:/var/lib/mysql
                networks:
                        - inception            			#network
                env_file: .env                  #env variables file
                restart: always         #restart if it stops 
                ports:
                 - "3306:3306"
        nginx:
               build: requirements/nginx
               image: nginx:1337
               container_name: nginx
               volumes:
                       - wordpress:/var/www/html
               networks:
                       - inception
               env_file: .env
               restart: on-failure 		#redemerer ssi en cas de crash 
               ports:
                       - "443:443" 		#on indique le port qui sera exposé a la machine locale
               depends_on:        			 #do not start nginx until wordpress is already started 
                       - wordpress
        wordpress:
                build: requirements/wordpress
                image: wordpress:1337
                container_name: wordpress
                volumes:
                        - wordpress:/var/www/html
                networks:
                        - inception
                env_file: .env
                restart: on-failure
                ports:
                  - "9000:9000"
                depends_on:    				
                        - mariadb
        redis:
                build: requirements/bonus/redis
                image: redis:1337
                container_name: redis
                volumes:
                        - wordpress:/var/www/html
                ports:
                  - "6379:6379"
                networks:
                  - inception
                depends_on:
                  - wordpress
                restart: always
        adminer:
                build: requirements/bonus/adminer
                image: adminer:1337
                container_name: adminer
                restart: always
                ports:
                  - "8080:8080"
                networks:
                  - inception
                depends_on:
                  - mariadb
        ftp-server:
                build: requirements/bonus/ftp-server
                image: ftp-server:1337
                container_name: ftp-server
                volumes:
                  - wordpress:/var/www/html
                restart: on-failure
                env_file: ./.env
                depends_on: 
                  - wordpress
                ports:
                  - "210:21"
                networks:
                  - inception
        netdata:
                build: requirements/bonus/netdata
                image: netdata:1337
                container_name: netdata
                restart: always
                ports:
                  - "3000:19999"
                networks:
                  - inception


networks:
        inception:
                driver: bridge

volumes:
        wordpress:
                driver: local #in this volume
                driver_opts:
                        type: 'none' 
                        device: '/home/admansar/data/wordpress' 
                        o: 'bind' #bind mount, means that its directly mapped to the directory with the container 
        mariadb:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '/home/admansar/data/mariadb'		

